---
name: Lint Review
on: [pull_request]
jobs:
  clj-kondo:
    name: runner / clj-kondo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - name: clj-kondo
        uses: nnichols/clojure-lint-action@v2
        with:
          pattern: "*.clj"
          clj_kondo_config: ".clj-kondo/config-ci.edn"
          level: "error"
          exclude: ".cljstyle"
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
